### ISSUE TITLE
[Feature Request] fal should be able to report on dbt test success/failure status

### ISSUE THREAD

**Issue by will-regal-voice** [fal-ai/fal#101]
Currently, I do something like `dbt run` then `fal run`, and one of the python scripts I have messages slack depending on the dbt model's success/failure status.  I'd like to be able to do something similar with dbt tests

**Comment by turbo1912** [comment]
100% agreed fal should be able to handle `dbt tests` as well. I believe we can implement this fairly quickly I will update this post once its ready for consumption
