### ISSUE TITLE
[Feature Request] `fal` should be able to run pre-hook python scripts, dbt, and post-hook python scripts from a single cli command 

### ISSUE THREAD

**Issue by turbo1912** [fal-ai/fal#108]
Introducing `fal flow`, this command should handle all dbt cli params and run dbt and fal in the right order.  
For example `fal flow run` should invoke `fal run --before`, `dbt run` and `fal run` in order with no regression in the `dbt run` behavior. 

This should also work for all other `dbt` commands, such as `dbt test`, `dbt build`.. 

This command will be more powerful when used with model selectors, for example:

```
When the following command is invoked:
"""
fal flow run --select modela
"""
Then following plan is calculated: 
"""
dbt run --select modela && fal run
"""
```

`fal flow` command also works with script selectors. 

Given the following dbt dag:
![image](https://user-images.githubusercontent.com/1714827/152219554-014ba273-f381-421e-851e-ae4b49ab1bff.png)

```
When the following command is invoked:
"""
fal flow run --select etl_script.py+
"""
Then following plan is calculated: 
"""
fal run --before etl_script.py &&
dbt run --select modela+  &&
fal run
"""

**Comment by chamini2** [comment]
merged https://github.com/fal-ai/fal/pull/149 and with this it does

```
dbt run {selection flags} &&
fal run {selection flags}
```

Still have to add --before handling

**Comment by chamini2** [comment]
Merged https://github.com/fal-ai/fal/pull/161 and now this works by using the cli `fal flow run`
