### ISSUE TITLE
fal running with DBT 0.19.0

### ISSUE THREAD

**Issue by cesar-loadsmart** [fal-ai/fal#116]
Hey folks, just a quick question, is it possible to run fal with dbt 0.19.0? if not, how long would it take to adapt fal to dbt 0.19.0?

**Comment by chamini2** [comment]
We currently don't support 0.19.0: https://github.com/fal-ai/fal#supported-dbt-versions

Changes between 0.19 and 0.20 are big enough in dbt's library that we decided to not support for now.

If its possible for your case, there is a [how-to by dbt](https://docs.getdbt.com/blog/upgrade-dbt-without-fear) on upgrading. You can join their Slack channel or our Discord server in case you have any questions regarding the upgrade.

**Comment by cesar-loadsmart** [comment]
Hey @chamini2, Appreciate it, thanks for replaying I'll try to upgrade my dbt version.

**Comment by chamini2** [comment]
Awesome! Let us know if it goes well and you are able to test fal!
