### ISSUE TITLE
write_to_source to Redshift makes strings varchar(256)

### ISSUE THREAD

**Issue by chamini2** [fal-ai/fal#120]
As discussed here: https://discord.com/channels/908693336280432750/940966301680156683

> https://docs.aws.amazon.com/redshift/latest/dg/r_Character_types.html#r_Character_types-text-and-bpchar-types
> > You can create an Amazon Redshift table with a TEXT column, but it is converted to a VARCHAR(256) column that accepts variable-length values with a maximum of 256 characters.
> > If you use the VARCHAR data type without a length specifier in a CREATE TABLE statement, the default length is 256. If used in an expression, the size of the output is determined using the input expression (up to 65535).
>
> I don't believe you can instruct from the pandas dataframe to use VARCHAR(65535)

**Comment by dnascimento** [comment]
If we use the dbt `model(dbt, fal)`, how can we change the type?

**Comment by chamini2** [comment]
This is a completely different interface. No way to achieve this right now
