### ISSUE TITLE
migrate to cloudpickle from dill

### ISSUE THREAD

**Issue by efiop** [fal-ai/fal#142]
> Also this makes a topic of migrating to cloudpickle (which I saw was discussed in the past in some places) relevant again, as it is nice to be able to dump our in-fal things (e.g. exceptions, so that we don't have to deploy our library version to the worker) by value but load things back by reference (so things like isinstance work). Patching out dill to handle that would rpobably not work as we'll need that serverside as well (e.g. won't be able to use new fal client with older server).

_Originally posted by @efiop in https://github.com/fal-ai/fal/issues/141#issuecomment-2021752029_

**Comment by efiop** [comment]
For the record: also ran into dilling errors in #143 that required `@mainify` on some new methods/classes, but this is probably another reason to look into cloudpickle with provides proper mechanisms instead of this crazy `__main__` magic that you have to do with dill.

**Comment by isidentical** [comment]
i think cloudpickle fixes #29 as well since it works out of the box with pydantic 2.5
