### ISSUE TITLE
fal: add ability to run apps in code

### ISSUE THREAD

**Issue by efiop** [fal-ai/fal#172]
Right now you need to find and hit the endpoint yourself, but it would be nice to be able to start and use the app natively in the code. E.g.

```
app.start()
app.endpoint_method(arg1, arg2)
```

Need to investigate how hard it would be to convert python inputs to json to send to the endpoint and then convert the results back. But maybe could just use dicts...

**Comment by jfischoff** [comment]
> But maybe could just use dicts.
Can't we use the output types we define?

**Comment by efiop** [comment]
@jfischoff Yes, I think we should be able to.

**Comment by efiop** [comment]
For the record, we have `AppClient.connect` now.
