### ISSUE TITLE
Show better HTTP failure details

### ISSUE THREAD

**Issue by chamini2** [fal-ai/fal#180]
A user sent this stack trace

```
HTTPStatusError                           Traceback (most recent call last)
Cell In[11], line 5
      2 recursive_interplation_passes = 1
      3 output_fps = 32 * (2**(recursive_interplation_passes))
----> 5 handler = fal_client.submit(
      6     "fal-ai/amt-interpolation",
      7     arguments={
      8         "video_url": public_url,
      9         "output_fps": output_fps,
     10         'recursive_interpolation_passes': recursive_interplation_passes,
     11     },
     12 )
     14 log_index = 0
     15 for event in handler.iter_events(with_logs=True):

File .../python3.11/site-packages/fal_client/client.py:356, in SyncClient.submit(self, application, arguments, path)
    349     url += "/" + path.lstrip("/")
    351 response = self._client.post(
    352     url,
    353     json=arguments,
    354     timeout=self.default_timeout,
    355 )
--> 356 response.raise_for_status()
    358 data = response.json()
    359 return SyncRequestHandle(
    360     request_id=data["request_id"],
    361     response_url=data["response_url"],
   (...)
    364     client=self._client,
    365 )

File .../python3.11/site-packages/httpx/_models.py:761, in Response.raise_for_status(self)
    759 error_type = error_types.get(status_class, "Invalid status code")
    760 message = message.format(self, error_type=error_type)
--> 761 raise HTTPStatusError(message, request=request, response=self)

HTTPStatusError: Client error '403 Forbidden' for url 'https://queue.fal.run/fal-ai/amt-interpolation'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403
```

The httpx `raise_for_status` method gives a very bad detail when failing. We should take the response's content and show that to the user instead. For example, for a 403 we get from the API:

```json
{"detail": "User is locked. Reason: Insufficient funds."}
```

**Comment by chamini2** [comment]
this probably applies for both fal client and fal

**Comment by chamini2** [comment]
Seeing more reports of this: https://discord.com/channels/908693336280432750/1228122613612810310

**Comment by phaabe** [comment]
it says on the website

> Get more free credits!
> Make an API request using a key and get more free credits!

but it returns 403 and now I am stuck with no good help.

**Comment by bruno-uy** [comment]
We're facing a similar issue with a 404 in the `audio_url` we're passing to the Wizper model.

In the playground you can see the detailed error, but it's hard to differentiate between failures if we don't have enough visibility on what happened in the background.

**Comment by bruno-uy** [comment]
I found a workaround to get the same information that I get on the playground:

<img width="395" alt="image" src="https://github.com/user-attachments/assets/9f570e30-537a-4cb6-9857-d7cdf384b851">

The steps are:
- Catch the exception as `variable`.
- Use `variable.response.content` to access the same output of the playground.
