### ISSUE TITLE
[Feature Request]Python script should be able to handle relative imports

### ISSUE THREAD

**Issue by RakibulHoque** [fal-ai/fal#184]
I was trying execute a script using `fal`, it works fine when full code is in a single script but breaks down when I write down my script to different modules. Probably this is because fal is internally using python's `exec` builtins function to execute the script after reading the file. Would appreciate it very much if you guys can add this feature to fal as soon as possible. It is a great tool to work with dbt.! :D

**Comment by mkam039** [comment]
Hi @RakibulHoque! Thanks for raising this issue. I can confirm that splitting code into modules doesn't yet work with fal. Will start working on it ASAP.

**Comment by RakibulHoque** [comment]
> Hi @RakibulHoque! Thanks for raising this issue. I can confirm that splitting code into modules doesn't yet work with fal. Will start working on it ASAP.

**Comment by RakibulHoque** [comment]
Thanks for quick response. :D
