### ISSUE TITLE
Add `upsert` and `overwrite` behaviors for `write_to_source`

### ISSUE THREAD

**Issue by omeroguz45** [fal-ai/fal#185]
## New features requested:

An ability to prevent duplication in certain table types.

- `mode` argument for `write_to_source()` function to determine how the data will be written to source:
  - `mode='write'`: Write data to source with no deduplication measures
  - `mode='append'`: Append data with respect to timestamps to prevent duplication of data with the same timestamp
  - `mode='update'`: Delete the contents of the table on the source and rewrite it

## Why is it needed?
 
The current `write_to_source` function just writes the data to the table via just adding it to the table. This creates an issue in certain tables; i.e time sensitive tables and tables that need to be updated. Deduplication measures can be taken to prevent the disruption to the table structures.

**Comment by chamini2** [comment]
As discussed in a meeting, let's do:

- `append`: the default behaviour that writes data to source with no deduplication measures
- `upsert`: based on a given column, do a typical UPSERT operation
  ```pgsql
  -- Postgres example
  INSERT INTO distributors (id_col, dname)
    VALUES (5, 'Gizmo Transglobal'), (6, 'Associated Computing, Inc')
    ON CONFLICT (id_col) DO UPDATE SET dname = EXCLUDED.dname;
  -- Note that the special excluded table is used to reference values originally proposed for insertion
  ```
- `overwrite`: Delete the contents of the table on the source and rewrite it

*****

Then, this would be passed in a `mode` argument

```py
def write_to_source(
        self,
        data: pd.DataFrame,
        target_source_name: str,
        target_table_name: str,
        mode: dict[str, str],
        dtype: Any = None,
):
```

and `mode` can have the values like

```
mode={'type': 'append'}
mode={'type': 'upsert', 'column': 'id_col'}
mode={'type': 'overwrite'}
```

or... we could do:

```
mode='append'
mode={'type': 'upsert', 'column': 'id_col'}
mode='overwrite'
```

or... we could add a new optional argument which we read only for `upsert` mode:

```
mode='append'
mode='upsert', upsert_column='id_col'
mode='overwrite'
```

**Comment by burkaygur** [comment]
I like the naming, and I like option 3 for the arg names.

**Comment by chamini2** [comment]
We did overwrite in #224, but have not done upsert yet. For now upsert is for the user (download the dataframe, update it locally, overwrite it) to do, since doing it on our side is not trivial (many adapters to support) and want to maybe consider how to do it better.

If anyone needs upsert, open a ticket and we will consider re-prioritizing it.
