### ISSUE TITLE
CLI hangs when user name contains special characters

### ISSUE THREAD

**Issue by mederka** [fal-ai/fal#210]
When user's full name contains special characters, such as `Ö` or `ş`, some fal commands just hang, e.g. `fal key list`. My suspicion is that it's a serialization issue.

**Comment by efiop** [comment]
Wow, great catch!

**Comment by efiop** [comment]
Though UserKeyInfo doesn't even contain user name, so not super clear right away where specifically it fails. Will need to take a closer look.
