### ISSUE TITLE
Publish Releases on Git Tag

### ISSUE THREAD

**Issue by squat** [fal-ai/fal#23]
Right releases are published to pypi by manually triggering the `release.yml` workflow, however I think it would be more semantic and a best practice to use Git tags to mark releases of the project and then use the `tag` event in CI to automatically trigger the steps needed to publish.

I think this is better because it:
* clearly indicates to the public what versions of the program exist, i.e. someone can look at all of the tags of the repo to know what versions have been released;
* allows for signing versions; and
* allows for checking out a specific version of the code using the release name.

**Comment by chamini2** [comment]
let's do it!

**Comment by efiop** [comment]
Fixed by https://github.com/fal-ai/fal/pull/177
