### ISSUE TITLE
Adding the --target flag to `fal run`

### ISSUE THREAD

**Issue by jakeluoma** [fal-ai/fal#261]
It would be very useful to be able to use fal with a dbt profile other than the default. For instance, I would want to be able to do `dbt run --target dev` followed by `fal run --target dev` where dev is not the default profile.

The current behavior is that fal does not recognize the --target flag, so I can't do `fal run --target dev` and I haven't found another way to get fal to recognize models that were run with a profile that is not the default.

For example, if I try doing `dbt run --target dev` followed by `fal run`, when fal runs I get the message:
`Unable to do partial parsing because config vars, config profile, or config target have changed`
and then when the script tries to retrieve the current model using a command like `faldbt.ref(current_model)`, the script crashes with the error:
`Exception: Could not get relation for 'model.<project>.<model>'`
even though that model was successfully run by dbt.

Is there a way to get fal to recognize models run with a non-default dbt profile that I'm not aware of? Or would that require the addition of the --target flag to fal?

Thank you!

**Comment by mkam039** [comment]
Hi @jakeluoma! Thanks for raising this issue! We indeed do not process the `--target` flag in fal yet. I'm looking into it now.

**Comment by jakeluoma** [comment]
Hi @mkam039, now that the PR is merged, I tested it out (dbt run --target dev; fal run) and everything works as expected. Thank you very much for implementing this!

**Comment by turbo1912** [comment]
fantastic! closing the PR please  re-open if you have any further questions
