### ISSUE TITLE
Delete account

### ISSUE THREAD

**Issue by 12kgChicken** [fal-ai/fal#272]
I tried your service, and it wasn't for me. So, I want to delete my account. 

I thought if I just simply logged out, everything would be gone, but then I got an email from Fal. So I tried to log back in, and github automatically gave Fal the oauth_access.create. I know all you're getting is my email address, and that's it, but that's still has a burden of getting spam emails (I know they're automated so I'm not blaming you for that). 

So I want to delete my account, remove the github token permanently unless I manually grant permission, and remove my email address from your system. Is that possible?

**Comment by pee-daddy-4** [comment]
> [FEA-3037 Delete account](https://linear.app/features-and-labels/issue/FEA-3037/delete-account)

You don't have access to this workspace.
Please contact the workspace admin to gain access.

What is this anyway??

**Comment by 12kgChicken** [comment]
> > [FEA-3037 Delete account](https://linear.app/features-and-labels/issue/FEA-3037/delete-account)
> 
> You don't have access to this workspace.
> Please contact the workspace admin to gain access.
> 
> What is this anyway??

Can you elaborate?

**Comment by pee-daddy-4** [comment]
> > > [FEA-3037 Delete account](https://linear.app/features-and-labels/issue/FEA-3037/delete-account)
> > 
> > 
> > You don't have access to this workspace.
> > Please contact the workspace admin to gain access.
> > What is this anyway??
> 
> Can you elaborate?

When I follow the link for the Linear bot, I get this message (even after creating an account). Did you figure out how to delete your account?

**Comment by 12kgChicken** [comment]
> > > > [FEA-3037 Delete account](https://linear.app/features-and-labels/issue/FEA-3037/delete-account)
> > > 
> > > 
> > > You don't have access to this workspace.
> > > Please contact the workspace admin to gain access.
> > > What is this anyway??
> > 
> > Can you elaborate?
> 
> When I follow the link for the Linear bot, I get this message (even after creating an account). Did you figure out how to delete your account?

Unfortunately, I didn't. I was waiting for a moderator to come and tell me how to do it. I thought you were the moderator. But it seems that this project will forever have my email address.

**Comment by pee-daddy-5** [comment]
> Unfortunately, I didn't. I was waiting for a moderator to come and tell me how to do it. I thought you were the moderator. But it seems that this project will forever have my email address.

Are you in the EU? If so, they are obligated to delete your data. Just write them a support mail!

**Comment by chamini2** [comment]
Please contact support@fal.ai for this.

**Comment by Stefan06072016** [comment]
Меня заблокировали, что делать?
