### ISSUE TITLE
fal flow run only runs the dbt model but not the fal script inside meta

### ISSUE THREAD

**Issue by deeprout** [fal-ai/fal#286]
I was trying to run `fal flow` but it does not run the python script defined inside the meta tag. `dbt run` followed by a `fal run` works as expected. 

```
> fal flow run --select netsuite_usd_exchange_rate_refined --target dev --experimental-flow
04:02:52  Found 422 models, 845 tests, 38 snapshots, 0 analyses, 441 macros, 0 operations, 0 seed files, 113 sources, 0 exposures, 0 metrics
Executing command: dbt --log-format json run --project-dir /Users/deepak.rout/code/dippr/dbt_pipelines --target dev --select netsuite_usd_exchange_rate_refined
Running with dbt=1.0.4
Found 422 models, 845 tests, 38 snapshots, 0 analyses, 441 macros, 0 operations, 0 seed files, 113 sources, 0 exposures, 0 metrics
Concurrency: 5 threads (target='dev')
1 of 1 START table model sandbox_staging.netsuite_usd_exchange_rate_refined..... [RUN]
1 of 1 OK created table model sandbox_staging.netsuite_usd_exchange_rate_refined [OK in 14.22s]
Finished running 1 table model in 38.77s.
```

**Comment by turbo1912** [comment]
@deeprout after having a second look at your example, you will have to run: 
```
fal flow run --select netsuite_usd_exchange_rate_refined+
```

Notice the `+`.. we designed `fal flow run` to behave exactly like the `dbt run`.  So `fal flow run` doesn't know about which dbt models ran before does whatever the graph selector (the plus sign) tells fal to do. I admit it's a little confusing now. 

We have some changes planned to make it more clear check out this issue for a better example; https://github.com/fal-ai/fal/issues/281

**Comment by deeprout** [comment]
Actually, we parse each model from the manifest and build airflow dag to run them. The command runs from airflow.

**Comment by deeprout** [comment]
It does.But we run multiple DBT run in a single instance/node at the same time.We change the target path so the files won't be overwritten by each other.How does  fal run behave in such scenario ? Will this correctly identify the context variables like model name based on the prior model ? If at a time multiple DBT runs are getting invoked ? Does it pick the value from any state file ?

**Comment by chamini2** [comment]
Hey, @deeprout, I think we would need to look a little bit into the details on how this is actually running for you. Curious on how you the target path for each of these runs? do you modify the dbt_project.yml or is there a flag maybe I don't know about?

fal just reads the `dbt_project.yml` and finds the `run_results.json` in the specified target path. Does this help you on how this works?

**Comment by chamini2** [comment]
Hey @deeprout , I think the closing comment in https://github.com/fal-ai/fal/issues/281#issuecomment-1190464724 may be of interest to you. Feel free to re-open if it does not address your issue.
