### ISSUE TITLE
Run jupyter notebooks `.ipynb` just like `.py` files

### ISSUE THREAD

**Issue by sungchun12** [fal-ai/fal#288]
**Problem**
fal can run python scripts but not jupyter notebooks natively
If I'm doing exploratory work in a notebook and want to automate that as part of the `fal flow run`, I have to refactor it as a python `.py` file. This adds redundant work that shouldn't be needed.

**Solution**
Allow `.ipynb` files to work 
![image](https://user-images.githubusercontent.com/19176976/166987008-47d3dc04-6828-46f1-b82d-4d43dff8be5e.png)

**Comment by mederka** [comment]
Hey @sungchun12! Thanks for raising this issue. We recently merged changes that should allow you to use notebook files as fal scripts. Here's how it works: https://fal-docs-cw7n0ro5b-features-and-labels.vercel.app/Docs/fal-cli/notebook-files

If it's OK with you, I will close this issue.
