### ISSUE TITLE
Let's use conventional commits

### ISSUE THREAD

**Issue by mederka** [fal-ai/fal#314]
**Is your feature request related to a problem? Please describe.**
We would like to have an automated way of tracking changes. This is ideally done by using a standardized commit message system.

**Describe the solution you'd like**
Let's use conventional commits: https://www.conventionalcommits.org/en/v1.0.0/

**Describe alternatives you've considered**
We could keep things the way they are

**Additional context**
Makes it easy to work with automated changelog generator, such as: https://github.com/orhun/git-cliff

**Comment by chamini2** [comment]
https://semver.org/
> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

Curious how git-cliff would handle major version 0. That is my main concern about automating this.

**Comment by mederka** [comment]
My thinking is that we can use git-cliff to generate a changelog for a part of our git history right before each release and we incorporate the changelog to our release message. No need to commit the changelog, as we will already have conventional commits to track changes.

Example git-cliff usage:

```
# From git-cliff readme

# only takes the latest tag into account
git cliff --latest

# only takes the current tag into account
# useful if you checkout a specific tag (e.g. `git checkout v0.0.1`)
# (requires a tag to be present for the current commit (i.e. HEAD))
git cliff --current

# generate changelog for unreleased commits
git cliff --unreleased
git cliff --unreleased --tag 1.0.0

# generate changelog for a specific commit range
git cliff 4c7b043..a440c6e
git cliff 4c7b043..HEAD
git cliff HEAD~2..
```

**Comment by mederka** [comment]
We're now using conventional commits
