### ISSUE TITLE
Make fal scripts __name__ == '__main__'

### ISSUE THREAD

**Issue by chamini2** [fal-ai/fal#328]
**Context**
When users test scripts they will normally have a 

```py
if __name__ == '__main__':
  main()
```

and the `main()` function will be where the whole script lives.

When a script is associated with a model, it is executed "directly". So it could be considered the "__main__" script.

**Describe alternatives you've considered**
Going for the dbt interface of offering a function.

```py
# for models
def model():
  pass
```

```py
# for hooks/after/before scripts
def hook():
  pass

**Comment by emekdahl-palmetto** [comment]
bump! we also ran into this when deploying to prod
