### ISSUE TITLE
I can not download ımages that generated by Flux 1 [dev] with LoRAs

### ISSUE THREAD

**Issue by 10xDijital** [fal-ai/fal#359]
Hello guys!

Also any authorised officer, I generate images with prompting text by using Flux.1 [dev] with LoRAs but ı can download. It was in the beginning properly worked. However after 20-30 downloads it started to not download nothing to my desktop. Then i changed my browser to fix this problem but it occured again this problem in the second browser ı used. So, ı have a brand to create ai contents. I am looking for a solution as soon as possible.

Please help me!

**Comment by chamini2** [comment]
Replied through email.
