### ISSUE TITLE
Add all models context in globals

### ISSUE THREAD

**Issue by chamini2** [fal-ai/fal#368]
**Context**
I would like to know about all the models status and test status in a [global script](https://docs.fal.ai/Docs/fal-cli/global-scripts).

**Describe the solution you'd like**
```py
for model in context.models:
  print(model.name, model.status)
```

**Describe alternatives you've considered**
Attaching an after script for each model there is.

**Comment by mederka** [comment]
Is this about the ergonomics of `context.models`? If not, you can achieve this with the `list_models` function, it should return a list of DbtModel object with test data in them.
