### ISSUE TITLE
Allow users to use ref, source, and context within a Juputer notebook

### ISSUE THREAD

**Issue by noel** [fal-ai/fal#38]
Given that the user has set up fal with the meta attributes, as I user I would like to do something like

```
import fal

df = ref(my_model)
df.iloc[0]

**Comment by chamini2** [comment]
Hey, @noel, an proposal on how this would work is available in #45. It's a draft and has some pending work, but it currently looks like this:

```py
from fal import FalDbt



faldbt = FalDbt(
    profiles_dir="/Users/user/.dbt",
    project_dir="/Users/user/Projects/iris",
)
faldbt.ref("iris")
df = faldbt.source("iris", "data")
# do some stuff with the dataframe
df2 = calc(df)
faldbt.write_to_source(df2, "iris", "result")
```

**Comment by chamini2** [comment]
Hello, @noel. Now it is possible to import `FalDbt` from `fal` package and use it in the way I showed above. Please give it a try and let me know if you run into any issues.

**Comment by noel** [comment]
I had missed the comment. I will give it a try
