### ISSUE TITLE
support Source Freshness

### ISSUE THREAD

**Issue by will-regal-voice** [fal-ai/fal#390]
**Context**
What are you trying to do and how would you want to do it differently? Is it something you currently cannot do?

after I run `dbt source freshness`, have fal be aware of the results and (possibly) run python scripts based on the results
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Is there an existing feature request for this?**
 * [x]  I have searched the existing issues

**Comment by chamini2** [comment]
Hey! I have opened the PR #404 to support this and it would be accessible through `source.freshness.status`, which could be 

- `'pass'`
- `'error'`
- `'warn'`
- `'runtime error'`

**Comment by chamini2** [comment]
Hey! We just released this in [v0.3.2](https://github.com/fal-ai/fal/releases/tag/v0.3.2). You can see how we use this here:
https://github.com/fal-ai/fal/blob/1aaddb169007b686935ad723c0d0eeb6bdba3012/integration_tests/projects/010_source_freshness/fal_scripts/freshness.py#L1-L15
