### ISSUE TITLE
Successfully installed catboost wants to import as _catboost

### ISSUE THREAD

**Issue by rm-minus-r-star** [fal-ai/fal#40]
I'm trying to use a model trained outside dbt to predict labels via python under dbt-fal

system deets:

```
Running with dbt=1.5.9
Registered adapter: fal=1.5.4
Registered adapter: postgres=1.5.9
```

fal-project.yml:

```
environments:
  - name: ml
    type: venv
    requirements:
      - scipy
      - pandas
      - numpy
      - statsmodels
      - catboost
```

catboost was just added, and the first run of the file below produced a long installation log to stdout, ending with 

`[builder]  [info]    Successfully installed [...] catboost-1.2.2 [...]`

Running the python model below with `dbt run select ...` gives me the subsequent error

```
from catboost import CatBoostRegressor
from pandas import concat

def model(dbt, fal):
    dbt.config(fal_environment="ml")

    df: pandas.DataFrame = dbt.ref("tr_rep_gentrification_prediction_inputs")

    X = df\
        .drop(['col0', 'col1', 'col2'], axis=1)\
        .fillna(0.0)

    model = CatBoostRegressor()
    model.load_model('cb_model.cbm')

    pred = model.predict(X)
    results = concat([df, pred], axis=0)

    return(results)
```

stdout:

  ```
No module named '_catboost'
22:55:01  1 of 1 ERROR creating python table model trans.tr_rep_gentrification_prediction_outputs  [ERROR in 42.02s]
22:55:02  
22:55:02  Finished running 1 table model in 0 hours 0 minutes and 58.89 seconds (58.89s).
22:55:02  
22:55:02  Completed with 1 error and 0 warnings:
22:55:02  
22:55:02  No module named '_catboost'

```
At the very least the module appears to be picking up a leading underscore. Why? This hasn't happened previously with any of the other imports.

**Comment by rm-minus-r-star** [comment]
Also posted [here](https://stackoverflow.com/questions/77829212/dbt-fal-python-package-failure-to-import-catboost).

**Comment by rm-minus-r-star** [comment]
Bizarrely, if I remove catboost from fal-project.yml and try to dbt run the file again, I get a similar error (as one would expect in this case) _but no leading underscore_.

> No module named 'catboost'
> 21:53:25  1 of 1 ERROR creating python table model trans.tr_rep_gentrification_prediction_outputs  [ERROR in 30.31s]
> 21:53:26  
> 21:53:26  Finished running 1 table model in 0 hours 0 minutes and 47.16 seconds (47.16s).
> 21:53:26  
> 21:53:26  Completed with 1 error and 0 warnings:
> 21:53:26  
> 21:53:26  No module named 'catboost'

**Comment by mederka** [comment]
But to solve your issue, you could try putting `from catboost import CatBoostRegressor` inside the model function definition.

**Comment by rm-minus-r-star** [comment]
@mederka Ohh, sorry! I've done so here https://github.com/fal-ai/dbt-fal/issues/915#issue-2089028341. Thanks for suggesting the fix, though I got the same error.
