### ISSUE TITLE
Referencing a fal script from a dbt dependancy does not work anymore in fal 0.3.1

### ISSUE THREAD

**Issue by mdutoo** [fal-ai/fal#412]
**Describe the bug**
Referencing a fal script from a dbt "local" dependancy does not work anymore, though it worked in 0.2.17.
Workaround : use another kind of dbt dependancy such as "package" (though it is not as practical for dev purposes).

**Your environment**
- OS: 
- Ubuntu 20.04.4 LTS, Python 3.8.10
- Paste the following commands output:
  ```
  fal --version
  0.3.1
  dbt --version
  1.0.1
  ```
- Adapter being used:  

**How to reproduce**
define a fal script in a dbt schema.yml using a path such as : dbt_packages/my_dbt_dependancy_project/scripts/my_fal_script.py
with my_dbt_dependancy_project being another dbt project installed as a "local" (unix soft link) dbt dependancy of this one.

I've tried using the fal-scripts-path: ../my_dbt_dependancy_project/scripts dbt var, but it also raises:
```  File "/usr/lib/python3.8/pathlib.py", line 908, in relative_to
    raise ValueError("{!r} does not start with {!r}"
ValueError: '/home/mdutoo/dev/ozwillo/workspace/fdr_appuiscommuns/scripts/publish.py' does not start with '/home/mdutoo/dev/ozwillo/workspace/fdr-eaupotable/../fdr_appuiscommuns/scripts'
```
Workaround : 

**Expected behavior**
It worked alright in fal 0.2.17 .

**Actual behavior**
This raises the following error:
```
 File "/home/mdutoo/dev/ozwillo/dbt-env/lib/python3.8/site-packages/fal/run_scripts.py", line 46, in run_scripts
    print_run_info(scripts)
  File "/home/mdutoo/dev/ozwillo/dbt-env/lib/python3.8/site-packages/fal/utils.py", line 9, in print_run_info
    models_str = "\n".join(map(lambda script: script.id, scripts))
  File "/home/mdutoo/dev/ozwillo/dbt-env/lib/python3.8/site-packages/fal/utils.py", line 9, in <lambda>
    models_str = "\n".join(map(lambda script: script.id, scripts))
  File "/home/mdutoo/dev/ozwillo/dbt-env/lib/python3.8/site-packages/fal/fal_script.py", line 146, in id
    return f"({self.model_name}, {self.relative_path})"
  File "/home/mdutoo/dev/ozwillo/dbt-env/lib/python3.8/site-packages/fal/fal_script.py", line 139, in relative_path
    return self.path.relative_to(self._faldbt.scripts_dir)
  File "/usr/lib/python3.8/pathlib.py", line 908, in relative_to
    raise ValueError("{!r} does not start with {!r}"
ValueError: '/home/mdutoo/dev/ozwillo/workspace/fdr_appuiscommuns/scripts/publish.py' does not start with '/home/mdutoo/dev/ozwillo/workspace/fdr-eaupotable'
```
**Screenshots**

**Additional context**

**Is there an existing bug report for this?**
 * [x ]  I have searched the existing issues

**Comment by chamini2** [comment]
Hello @mdutoo, thanks for reaching out. If I understand correctly, you are trying to use scripts from a project outside of the current project, right?


It would be like having this file structure
```
├── some_project
│   ...
│   ├── dbt_project.yml
│   ├── macros
│   └── models
└── other_project
    ...
    ├── dbt_project.yml
    ├── scripts
        └── publish.py
    ├── macros
    └── models
```

And using `publish.py` from a model in `some_project`?

**Comment by mdutoo** [comment]
Yes, that's it, that's my need.
And thanks for your quick reply !

**Comment by chamini2** [comment]
Hey, @mdutoo I have checked with the team and this was not really intentionally supported before and we have introduced some changes that break this. Currently, we do not plan to support importing scripts from outside your dbt project. Although this may change in the future.

For now, I can offer you two ideas:

1. You can copy the scripts you need from the other project into the current project and keep 2 copies of these files.
2. Another option is to create a Python package and import it into both your dbt projects.

**Comment by mdutoo** [comment]
Thank you for your analysis, I understand. 
Yes, that's what I do, right now I copy scripts. Referring to scripts within dbt dependency packages woould have been cleaner and maybe I'm not the one with this use case, but it works as is.

BTW now I'm afraid of telling you about my workarounds for other features, for fear of you disabling them ;)

**Comment by chamini2** [comment]
Closing this, but feel free to reopen or comment about this if you or anyone else wants!
