### ISSUE TITLE
Can this suppot dbt version 1.2.0?

### ISSUE THREAD

**Issue by JimmyPoh88** [fal-ai/fal#521]
Hi, currently my dbt is running using version 1.2.0. Is it possible to run this without any issue?

**Comment by chamini2** [comment]
Hello, @JimmyPoh88. Thanks for asking. dbt 1.2.* **is** currently supported by fal, I will add this information to the README, since it seems we forgot.

Cheers!

PD: integration tests for 1.2: https://github.com/fal-ai/fal/actions/runs/2972497791
