### ISSUE TITLE
fal run --scripts selector with global scripts not working

### ISSUE THREAD

**Issue by jorserpl** [fal-ai/fal#568]
**Describe the bug**
Fal CLI `run` command using `--scripts` flag selector does not execute any script when the script passed is under the `before` key in the `schema.yml` configuration.

**Your environment**
- OS: macOS Monterrey 12.6
- Paste the following commands output:
```
fal --0.6.0
dbt --1.2.1
```
- Adapter being used: bigquery

**How to reproduce**
Add scripts to run under `--before` key in the `schema.yml`:
```
version: 2

fal:
  scripts:
    before:
      - fal_scripts/delete_bq_datasets.py
      - fal_scripts/download_prod_artifacts.py
```
File structure:
```
dbt_project
├── analysis
├── dbt_packages
├── dbt_project.yml
├── fal_scripts
│   ├── delete_bq_datasets.py
│   └── download_prod_artifacts.py
├── logs
├── macros
├── models
│   ├── exposures
│   └── schema.yml
├── packages.yml
├── seeds
├── snapshots
├── target
└── tests

```
Then run:
```sh
fal run --before --scripts download_prod_artifacts.py
```
Or:
```sh
fal run --scripts download_prod_artifacts.py
```

**Expected behavior**
Run only the script passed to the `--scripts` flag: `download_prod_artifacts.py`.  

**Actual behavior**
Does nothing for neither case.

```sh
fal run --scripts download_prod_artifacts.py
```
```
13:25:19  Found 370 models, 544 tests, 0 snapshots, 18 analyses, 583 macros, 0 operations, 42 seed files, 129 sources, 2 exposures, 0 metrics
13:25:19  Could not read dbt sources artifact
```
```sh
fal run --before --scripts download_prod_artifacts.py
```
```
13:27:34  Found 370 models, 544 tests, 0 snapshots, 18 analyses, 583 macros, 0 operations, 42 seed files, 129 sources, 2 exposures, 0 metrics
13:27:34  Could not read dbt sources artifact
```
**Additional context**
The issue might be [this](https://github.com/fal-ai/fal/blob/771ad3dc8946dbda57e91b188719f8a20c6eb353/src/fal/cli/fal_runner.py#L47) section of code (related with `scripts` and `global_scripts` variables).

**Comment by mederka** [comment]
Thanks for raising this issue, @jorserpl ! We're looking into it.

**Comment by mederka** [comment]
@jorserpl, quick update! We just merged a fix into `main` and will be releasing it in our next patch. In the meantime you can test it by cloning this repository and running `pip install -e .` inside the repository directory.
