### ISSUE TITLE
write_to_model specifying the model does not work unless we manually create the ephemeral

### ISSUE THREAD

**Issue by polmonso** [fal-ai/fal#709]
I'm not sure if it's a bug or a feature request.

We have some legacy code that must output three tables instead of the classic just-one.

We haven't found anybody doing this  and there are very little references as to whether is supported.

Anyhow, we've noticed that if we manually create the ephemeral sql it just works.

```
fal --version: fal 0.7.6
dbt --version: 1.3.1*
```
sidenote: running that gave us the error `AssertionError: fal credentials must have a db_profile property set`

Which they do and fal flow and dbt run do work normally so 🤷🏽 

- Adapter being used:  postgres

**How to reproduce**
fal model:
```
dfrefpg = ref("raw_pg")
df_tuturu = ref("raw_tuturu")

write_to_model(dfrefpg)
write_to_model(data=df_tuturu, target_1='tuturu')
```

**Expected behavior**
to generate the tuturu table if it doesn't exist.

**Actual behavior**
RuntimeError: Could not find source 'db_mercat'.'tuturu'

**Additional context**
on dataframe is the result and another output dataframe is which "products" where used in the calculation.

**Comment by burkaygur** [comment]
Hi @polmonso ! Thank you for reporting this. Synced on the Discord community and the issue seems to be resolved. We are working on docs to make things more clear. But let us know if there are particular docs that you'd like to see updated.
