### ISSUE TITLE
Using fal with Dbt Cloud

### ISSUE THREAD

**Issue by khookguy** [fal-ai/fal#76]
How can we install and run fal in Dbt Cloud?

**Comment by burkaygur** [comment]
Hi @khookguy! We just started writing down our thoughts on how fal could work with dbt Cloud here: #79 

Would love to get your feedback on it! You can also join our Discord server [here](https://discord.gg/Fyc9PwrccF).

**Comment by burkaygur** [comment]
We can deliver this pretty fast if you like our solution! Let us know.

**Comment by burkaygur** [comment]
@khookguy we just implemented this proposal and [wrote a blog post on it](https://blog.fal.ai/how-to-run-python-with-dbt-cloud-hint-no-need-for-airflow/). 

As part of the implementation, we also published a new [Github Action to trigger dbt Cloud runs](https://github.com/marketplace/actions/dbt-cloud-action). 

Looking forward to your feedback. 

[Join us on Discord](https://discord.gg/Fyc9PwrccF) or the #tools-fal channel on [dbt Slack](https://www.getdbt.com/community/join-the-community).
