### ISSUE TITLE
unable to install dbt-fal[bigquery]

### ISSUE THREAD

**Issue by marcNY** [fal-ai/fal#811]
**Describe the bug**
When running pip install dbt-fal[bigquery] i get zsh: no matches found: dbt-fal[bigquery]

**How to reproduce**
On mac osx use pip install dbt-fal[bigquery] 

**Expected behavior**
installation of  dbt-fal[bigquery] 

**Actual behavior**
I get the message:  zsh: no matches found: dbt-fal[bigquery]

**Comment by mederka** [comment]
Thank you for raising this, @marcNY. Could you tell us which versions of Python and dbt-bigquery you are using?

**Comment by chamini2** [comment]
@marcNY, you need to enclose the package in quotes. Brackets are [picked up by zsh and treated differently](https://kinopyo.com/en/blog/escape-square-bracket-by-default-in-zsh). 

Try

```sh
pip install 'dbt-fal[bigquery]'
```

**Comment by burkaygur** [comment]
Hi @marcNY! Where you able to run @chamini2's recommendation successfully? If yes, I would like to close the ticket.
