### ISSUE TITLE
Upgrade to dbt=1.0.0  

### ISSUE THREAD

**Issue by nicolasberbigier** [fal-ai/fal#83]
Upgrade to dbt=1.0.0 seems to break fal 
fal tries to search for 
source-paths: ["models"] in dbt_project.yml whereas this is deprecated in dbt=1 
and replaced by 
model-paths: ["models"]

**Comment by turbo1912** [comment]
thanks @nicolasberbigier we are actively working on this please follow https://github.com/fal-ai/fal/pull/69. I will make sure to update this ticket when that PR is merged in.

**Comment by chamini2** [comment]
@nicolasberbigier , we have just released a version compatible with dbt 1.0.0. 

```
pip install fal==0.1.35
```

Please let us know how it goes and if anything else comes up!
