### ISSUE TITLE
fal is not compatible with dbt 1.5.0

### ISSUE THREAD

**Issue by roberto-rosero** [fal-ai/fal#846]
We upgraded the dbt version to 1.5.0, but when this upgrade finished it says that the version of dbt is not compatible with fal (0.8.6)

**Comment by mederka** [comment]
Hey there @roberto-rosero! Sorry for the inconvenience. We're actively working on getting fal to support dbt 1.5 (https://github.com/fal-ai/fal/pull/841), there are still some rough edges to iron out, but we should have it ready sometime soon. We will let you know as soon as it's ready.

**Comment by roberto-rosero** [comment]
thanks @mederka !!

**Comment by chamini2** [comment]
To upgrade, run `pip install 'fal[<adapter>==0.9.0'` and let us know if anything is not working as expected!
