### ISSUE TITLE
Consider how to run fal in a fresh environment

### ISSUE THREAD

**Issue by chamini2** [fal-ai/fal#86]
Right now, we use dbt's [`run_results.json`](https://docs.getdbt.com/reference/artifacts/run-results-json) artifact  to decide which models to run based on status.

A use case [presented in the Discord channel](https://discord.com/channels/908693336280432750/908693336280432755/922375589074178089) is running in a fresh environment where there is no artifacts.

This happens by running each step in a different pod (Airflow):

```python
PodOperator(dbt run -m model) >> \
  PodOperator(dbt test -m model) >> \
  PodOperator(fal run -m model -s script_name)
```

Notice the proposal has a `-m` that works like dbt's and `-s` for a specific script of the model.

**Comment by chamini2** [comment]
Maybe we could start by handling `-m` and `-s` stays up for discussion.

The behaviour I would expect is, if I pass in `--all` or `--model`, it will ignore the `run_results.json`

**Comment by turbo1912** [comment]
```
if I pass in --all or --model, it will ignore the run_results.json
```
I agree with this.. 

and then this brings up a related question how do we error out when there is no `run_results.json`? we should probably update that message to include information about `--all` and `--model`

**Comment by chamini2** [comment]
Agreed. Do we want to wait for more feedback or should we start adding `--model`?

**Comment by chamini2** [comment]
We talked on a meeting about leveraging the dbt flagging system instead of implementing `--model` manually.

**Comment by chamini2** [comment]
If I pass in --all or selection flags, it will ignore the run_results.json for deciding which models to run.
If run_results.json available, it will still load status information to pass to models; if it's not available, it still runs, but shows a warning.


If there is no run_results.json and I did not pass --all or selection flags, fail with exception about not having a way to decide which models to run.
